apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rand
  name: rand
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rand
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rand
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
